# Generated by Django 5.0.4 on 2024-04-25 01:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DIRECTOR', 'DIRECTOR'), ('ACTOR', 'ACTOR')], max_length=50)),
            ],
            options={
                'db_table': 'cast_member',
            },
        ),
    ]
