# Generated by Django 5.0.4 on 2024-04-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
